Django/BazarKori/BazarKori/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView
from accounts.views import HomeView
from rest_framework import routers

from django.contrib import admin
from django.contrib.auth import views as auth_views
from products.views import *
from products import views
from django.conf import settings
from django.conf.urls.static import static


#APi router and paths
router = routers.DefaultRouter()
#check API endpoint
router.register('api/products', views.ItemViewSet)

admin.autodiscover()



urlpatterns = [

	path('home/',HomeView.as_view(),name='home'),

    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

    path('api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    path('', include(router.urls)),

	path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),

    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
	path('products/', include('products.urls')),
    path('search/',include('search.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
   



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/BazarKori/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import HomeView

app_name = 'accounts'

urlpatterns=[
	# /accounts/

	path('signup/',views.signup,name='signup'),
	
	#This url in main settings
	#path('',HomeView.as_view(),name='home'),


]

Django/BazarKori/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
	#/cart
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

     #/products/category/<category_id>/
    #path('category/<int:item_id>/',views.category_product,name='category_product'),
]

Django/BazarKori/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator

# Create your models here.

from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator

Django/BazarKori/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

Django/BazarKori/accounts/views.py
#from django.shortcuts import render,redirect
#from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from products.models import Inventory,Item
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from accounts.forms import SignUpForm
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


class HomeView(TemplateView):
	print("called")
	template_name = 'home.html'

	def get(self,request):
		print("get home")
		#Check If anonymous user
		if(request.user.is_authenticated ):
			user_name = request.user.get_full_name()
			context = {
				"user_name":user_name
			}
		else :
			user_name = "Guest"
			context = {
					"user_name":user_name
				}
		return render(request,self.template_name,context) 



	def get_featured_data(self,request):
		
		print("featured funstion")
		context = Item.objects.filter(title__contains="Ban")
		user_name = request.user.get_full_name()
		context = {
			"featured_products":featured_products,
			"user_name":user_name
		}

		return render(request,self.template_name,context) 



Django/BazarKori/accounts/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load static %}
{% block search_content %}
{% endblock %}
{% block title %}This is The Home Page{% endblock %}

{% block content %}
<!-- HOME -->
<div id="home">
	<!-- container -->
	<!--<img src="{% static 'img/logob1.png' %}"  class="img-rounded" alt="Cinque Terre" width="180" height="180">-->
	
		<div class="container">
			<!-- home wrap -->
			<div class="home-wrap">
				<!-- home slick -->
				<div id="home-slick">
					<!-- banner -->
					<div class="banner banner-1">
						<img src="{% static 'img/veg.jpeg' %}" alt="">
						<div class="banner-caption text-center">
							<h1  class="white-color font-weak" >Bazar Kori.Com</h1>
							<h3 class="white-color font-weak">we supply the best product</h3>
							<button class="primary-btn">shop now</button>
						</div>
					</div>
					<!-- /banner -->

					<!-- banner -->
					<div class="banner banner-1">
						<img src="{% static 'img/veg.jpeg' %}" alt="">
						<div class="banner-caption">
							<h1 class="primary-color">BAZAR KORI<br><span class="white-color font-weak">Save Up to 50% OFF</span></h1>
							<button class="primary-btn">Shop Now</button>
						</div>
					</div>
					<!-- /banner -->

					<!-- banner -->
					<div class="banner banner-1">
						<img src="{% static 'img/veg.jpeg' %}" alt="">
						<div class="banner-caption">
							<h1 class="white-color">New Product <span>Collection</span></h1>
							<button class="primary-btn">Shop Now</button>
						</div>
					</div>
					<!-- /banner -->
				</div>
				<!-- /home slick -->
			</div>
			<!-- /home wrap -->
		</div>
		<!-- /container -->
		<div class="container-fluid">
			<div class="page-header">
				
			</div>

			<!--Featured Products-->
			{% if featured_products %}
				{% for item in featured_products %}
								<!-- banner -->
								<p>Fetaured-{{item.title}}</p>
				{% endfor %}
			{% else %}
				
			{% endif %}
			
						<!-- /banner -->
			<!--Urls-->
			<div class="container">
				<div class="row">
			    		<div class="col-sm">
							<a href="{% url 'products' %}" class="btn btn-success">Product Page</a>
							
						</div>
						<br>
						<div class="col-sm">
							<a href="{% url 'search_result' %} "class="btn btn-info">Search Page</a>
						</div>
						<div class="col-sm">
							<a href="{% url 'speech_result' %} "class="btn btn-info">Voice Search</a>
						</div>
						<div class="col-sm">
							<a href="{% url 'auto_complete_search' %} "class="btn btn-info">Auto Complete Search</a>
						</div>
						<div class="col-sm">
							<a href="{% url 'cart_detail' %} "class="btn btn-info">Shopping Cart</a>
						</div>
						<br>
						<div class="col-sm">
							<a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
						</div>
						<br>
						<div class="col-sm">
							<a href="{% url 'home' %}" class="btn btn-primary">Home</a>
						</div>
				</div>
			</div>
			
			<div id="featured">
				{% for item in featured_products %}
					<h4>Feature Item-{{ item.title }}</h4>
				{% endfor %}
				
			</div>

			{% if user.is_authenticated %}

			<br>
			 <h2> username: {{ user.username }}! </h2>
			 <h2> Hi {{ user_name }}! </h2>
			 <br>

			  <a href="{% url 'logout' %}" class=" btn btn-danger">logout</a>

			{% else %}
			  <p>You are not logged in</p>
			  <a href="{% url 'login' %}" class="btn btn-primary">login</a>

			  <p><strong>-- OR --</strong></p>

			   <a href="{% url 'social:begin' 'twitter' %}" class="btn btn-primary">Login with Twitter</a>
			   <a href="{% url 'social:begin' 'github' %}" class="btn btn-primary">Login with GitHub</a>
			   
			{% endif %}
		</div>
	{% endblock %}
</div>

Django/BazarKori/accounts/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
</div>
{% endblock %}